# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "NDGL-iOS-Workspace")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end

### Device Management

 desc "Register Devices"
 lane :register_new_device do  |options|
   device_name = prompt(text: "Enter the device name: ")
   device_udid = prompt(text: "Enter the device UDID: ")
   device_hash = {}
   device_hash[device_name] = device_udid
   register_devices(devices: device_hash)
   match(type: "development", force_for_new_devices: true)
 end